name: CD

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/cd.yml' # Only if triggered manually or change the cd file
    
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configs:
          - { name: "web", extension: ".wasm", goarch: "GOARCH=wasm", goos: "GOOS=js" }
          - { name: "windows", extension: ".exe", goarch: "", goos: "GOOS=windows" }
          - { name: "linux", extension: "", goarch: "", goos: "GOOS=linux" }
    permissions:
      contents: write
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      PROJECT_NAME: space-go
      PROJECT_BUILD_PATH: build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'
        cache-dependency-path: src/go.sum
    - name: Set up Dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y --no-install-recommends libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config

    - name: Copy Web Dependencies
      if: matrix.configs.name == 'web'
      run: |
        cd src
        cp index.html ../${{ env.PROJECT_BUILD_PATH }}/
        cp wasm_exec.js ../${{ env.PROJECT_BUILD_PATH }}/

    - name: Build
      run: |
        cd src

        env ${{ matrix.configs.goos }} ${{ matrix.configs.goarch }} go build -ldflags "-s -w" -o ../${{ env.PROJECT_BUILD_PATH }}/space-go${{ matrix.configs.extension }} github.com/maiconpintoabreu/space-go
    
    - name: Generate Artifacts
      run: |
        cp README.md ${{ env.PROJECT_BUILD_PATH }}
        cp LICENSE ${{ env.PROJECT_BUILD_PATH }}
        ls ${{ env.PROJECT_BUILD_PATH }}
        7z a ./${{ env.PROJECT_NAME }}.zip ./${{ env.PROJECT_BUILD_PATH }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}-${{ matrix.configs.name }}.zip
        path: ./${{ env.PROJECT_NAME }}.zip

    - name: Download + Authorize Butler
      run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

    - name: Login To Butler
      run: ./butler login

    - name: Push to Itch
      run: ./butler push ${{ env.PROJECT_BUILD_PATH }} maiconspas/space-go:${{ matrix.configs.name }}