name: Linux

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/linux.yml' # Only if triggered manually or change the cd file
    
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      PROJECT_NAME: space-go
      PROJECT_BUILD_PATH: build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Build
      run: |
        cd src
        env GOOS=linux go build -ldflags "-s -w"  -o ../${{ env.PROJECT_BUILD_PATH }}/space-go.exe github.com/maiconpintoabreu/space-go
    
    - name: Generate Artifacts
      run: |
        cp README.md ${{ env.PROJECT_BUILD_PATH }}
        cp LICENSE ${{ env.PROJECT_BUILD_PATH }}
        ls ${{ env.PROJECT_BUILD_PATH }}
        7z a ./${{ env.PROJECT_NAME }}.zip ./${{ env.PROJECT_BUILD_PATH }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}.zip
        path: ./${{ env.PROJECT_NAME }}.zip

    - name: Download + Authorize Butler
      run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

    - name: Login To Butler
      run: ./butler login

    - name: Push Windows to Itch
      run: ./butler push ${{ env.PROJECT_BUILD_PATH }} maiconspas/space-go:windows